development:
  adapter: postgresql
  encoding: unicode
  database: open_food_network_dev_s2
  pool: 5
  host: localhost
  username: ofn
  password: f00d

test:
  adapter: postgresql
  encoding: unicode
  database: open_food_network_test_s2
  pool: 5
  host: localhost
  username: ofn
  password: f00d

#not used with heroku
production:
  adapter: postgresql
  encoding: unicode
  database: open_food_network_prod
  pool: 5
  username: ofn
  password: f00d

staging:
  adapter: postgresql
  encoding: unicode
  database: open_food_network_prod
  pool: 5
  username: ofn
  password: f00d
